In [1]:
from inference import Inference

In [2]:
import numpy as np
import h5py
from matplotlib import pyplot as plt
from pathlib import Path
from cellpose import models, utils, plot

In [3]:
import IPython

%load_ext autoreload
%autoreload 2

In [4]:
# Open the HDF5 file
DATA_FOLDER = Path("w:/")
filepath = DATA_FOLDER / "sample01.pre"
file = h5py.File(filepath, 'r')

# Access the dataset
amplitude = file['amplitude/images']
phase = file['phase/images']

img_idx = 2

phase_img = phase[img_idx]
amplitude_img = amplitude[img_idx]

In [7]:
segmentation_method = "threshold"
classification_method = "SVC"

In [8]:
inf = Inference(segmentation_method, classification_method)

In [9]:
masks = inf._segment(phase_img, amplitude_img)

In [10]:
extracted_features = inf._extract_features(phase_img, amplitude_img, masks)

extracted_features.head()

Volume  Roundness    Opacity  AmplitudeVariance  AmplitudeSkewness  \
0  192.524927   0.678201  12.129739           0.000993           0.298412   
1  234.584219   0.902549  12.119352           0.001275           0.865625   
2  810.974232   0.551416  12.111987           0.001551           0.457676   

   MaxAmplitude  MinAmplitude  DryMassDensity  MaxPhase  MinPhase  ...  \
0      0.109802     -0.031372        0.086269  3.376953 -0.196045  ...   
1      0.149048     -0.031372        0.105285  3.679688 -0.199219  ...   
2      0.156860     -0.039215        0.048304  3.490234 -0.595703  ...   

   PhaseSTDLocalKurtosis  PhaseSTDLocalMin  PhaseSTDLocalMax  \
0               2.588414          0.008264          1.057671   
1               1.904920          0.009170          0.831745   
2               3.507869          0.006217          1.358430   

   AmplitudeSTDLocalMean  AmplitudeSTDLocalVariance  \
0               0.021312                   0.000059   
1               0.021361                   0.000186   
2               0.024285                   0.000143   

   AmplitudeSTDLocalSkewness  AmplitudeSTDLocalKurtosis  AmplitudeSTDLocalMin  \
0                   0.348337                   2.563706              0.003978   
1                   0.876491                   3.169161              0.002021   
2                   0.555126                   2.708117              0.002428   

   AmplitudeSTDLocalMax  MaskID  
0              0.041151       0  
1              0.063593       1  
2              0.057923       2  

[3 rows x 25 columns]

In [11]:
predictions, probabilities = inf._classify(extracted_features)

print(predictions)
print(probabilities)

[b'agg' b'rbc' b'agg']
[[0.50437371 0.07585851 0.02021279 0.25875934 0.14079565]
 [0.13910853 0.05839536 0.01805084 0.62988216 0.15456311]
 [0.57751607 0.21977403 0.0558597  0.05483745 0.09201275]]
